const SCOPE = 'app/customer/list'

export const LOAD_CUSTOMER_LIST = SCOPE + '/LOAD_CUSTOMER_LIST';
export const LOAD_CUSTOMER_LIST_SUCCESS = SCOPE + '/LOAD_CUSTOMER_LIST_SUCCESS';
export const LOAD_CUSTOMER_LIST_ERROR = SCOPE + '/LOAD_CUSTOMER_LIST_ERROR';

export const LOAD_CUSTOMER = SCOPE + '/LOAD_CUSTOMER';
export const LOAD_CUSTOMER_SUCCESS = SCOPE + '/LOAD_CUSTOMER_SUCCESS';
export const LOAD_CUSTOMER_ERROR = SCOPE + '/LOAD_CUSTOMER_ERROR';





