const SCOPE = 'app/customer/list'

export const LOAD_CUSTOMER_LIST = SCOPE + '/LOAD_CUSTOMER_LIST';
export const LOAD_CUSTOMER_LIST_SUCCESS = SCOPE + '/LOAD_CUSTOMER_LIST_SUCCESS';
export const LOAD_CUSTOMER_LIST_ERROR = SCOPE + '/LOAD_CUSTOMER_LIST_ERROR';


